services:
    db:
        build: requirements/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        ports:
            - "3306:3306"
    server:
        build: requirements/nginx
        restart: always
        depends_on:
          - db
        ports: 
            - "8080:80"
