services:
    # MARIADB
    db:
        container_name: mariadb
        build: requirements/mariadb
        env_file:
            - ./.env
        volumes:
            - mariadb:/var/lib/mysql
        restart: always
        networks:
            - inception-net
    # NGINX
    server:
        container_name: nginx
        build: requirements/nginx
        volumes:
            - wordpress:/var/www/html
        restart: always
        depends_on:
          - wordpress
        ports: 
            - "443:443"
        networks:
            - inception-net
        env_file:
            - ./.env
    # WORDPRESS
    wordpress:
        container_name: wordpress
        depends_on:
          - db
        build: requirements/wordpress
        env_file:
            - ./.env
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception-net
        restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/itahri/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/itahri/data/mariadb
      o: bind

networks:
    inception-net:
        driver: bridge




#home/login/data/volume_name
